default['scalr']['version'] = "2.2.1"
default['scalr']['checksum'] = "c7c28d84950c0bd79fd1a311c0967fa820516ae1"
default['scalr']['dir'] = "/var/www/scalr"
default['scalr']['db']['database'] = "scalrdb"
default['scalr']['db']['user'] = "scalrsuser"
default['scalr']['user'] = "root"
default['scalr']['group'] = "root"